name: Deploy to Server

on:
  workflow_run:
    workflows: ["Build Next JS aplication"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download Next.js artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-standalone

      - name: Upload to Server
        run: scp -r .next/standalone ${{ secrets.SSH_LOGIN }}:${{ secrets.SSH_DIR_PATH }}
