name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: cp -r public .next/standalone/public
      - run: cp -r .next/static .next/standalone/.next/static
      - run: mv .next/standalone/server.js .next/standalone/app.js
      - uses: actions/upload-artifact@v4
        with:
          name: nextjs-standalone
          path: .next/standalone
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - uses: actions/checkout@v3

#       - name: Download Next.js artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: nextjs-standalone
#           path: .next/standalone

#       - name: Copy file to a server
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: 22
#           source: ".next/standalone/*"
#           target: ~/domains/${{ secrets.SSH_DOMAIN_NAME }}/public_nodejs/
#           strip_components: 2

#   restart:
#     runs-on: ubuntu-latest
#     needs: deploy

#     steps:
#       - name: executing remote ssh commands
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: 22
#           script: devil www restart ${{ secrets.SSH_DOMAIN_NAME }}
